server:
  port: 8080
  context-path: /
  

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3307/db_jxc2
      username: root
      password: 123456
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false